baseURL = 'https://rubatotree.github.io/blog/'
locale = 'en-us'
haveCJKLanguage = true
timeZone = 'Asia/Shanghai'
title = "Umbrella Coffee"
theme = 'PaperMod'

[params]
env = 'production'
defaultTheme = 'auto'
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowToc = true
math = true
comments = true

images = ["images/og-default.png"]

[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon.ico"
favicon32x32 = "favicon.ico"

[params.homeInfoParams]
Title = "欢迎来到雨伞咖啡店！☕☂️"
Content = """
Tech & Art & Kawaii blog, by [@rubatotree](https://github.com/rubatotree/)
"""

[[params.socialIcons]]
name = "email"
url = "mailto:zhuyutian@mail.ustc.edu.cn"

[[params.socialIcons]]
name = "github"
url = "https://github.com/rubatotree"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/ruaruatree"

[[params.socialIcons]]
name = "itchio"
url = "https://rubatotree.itch.io/"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@rubatotree"

[[params.socialIcons]]
name = "bilibili"
url = "https://space.bilibili.com/3494360710646642"

[[params.socialIcons]]
name = "Xiaohongshu"
icon = "xiaohongshu"
url = "https://www.xiaohongshu.com/user/profile/653b6aeb000000000301d9ed"


[markup.typst]
root = "./content"
packagePath = "./packages"
jobs = 4

[markup.typst.watch]
enabled = true
timeout = "3s"

[[menu.main]]
identifier = "档案"
name = "档案"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "友链"
name = "友链"
url = "/friends/"
weight = 40

[[menu.main]]
identifier = "学术"
name = "学术"
url = "https://rubatotree.github.io/academic/"
weight = 45

[[menu.main]]
identifier = "搜索"
name = "搜索"
url = "/search/"
weight = 50

[outputs]
home = ["HTML", "RSS", "JSON"]
