#!/usr/bin/env python3
"""Generate the RSS 2026 Typst paper catalog from captured JSON metadata."""

from __future__ import annotations

import argparse
import json
import tempfile
from collections import OrderedDict
from pathlib import Path
from typing import Any


DEFAULT_INPUT = Path("data/rss2026/papers.json")
DEFAULT_OUTPUT = Path("content/posts/rss26-paper-catalog.typ.inc")


def _typst_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def load_papers(path: Path) -> list[dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    papers = payload.get("papers")
    if not isinstance(papers, list) or not papers:
        raise ValueError(f"no papers found in {path}")
    return sorted(papers, key=lambda paper: int(paper["paper_id"]))


def render_catalog(papers: list[dict[str, Any]]) -> str:
    sessions: OrderedDict[str, list[dict[str, Any]]] = OrderedDict()
    for paper in papers:
        sessions.setdefault(str(paper["session"]), []).append(paper)

    lines = [
        "// Generated by tools/rss2026/generate_typst_catalog.py. Do not edit manually.",
        "",
    ]
    for session, session_papers in sessions.items():
        lines.append(f'== #text("{_typst_string(session)}")')
        lines.append("")
        for paper in session_papers:
            paper_id = int(paper["paper_id"])
            title = _typst_string(str(paper["title"]))
            detail_url = _typst_string(str(paper["detail_url"]))
            lines.append(f'- #link("{detail_url}", "{paper_id}. {title}")')
        lines.append("")
    return "\n".join(lines)


def write_text(content: str, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=output.parent, prefix=f".{output.name}.", delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.replace(output)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    papers = load_papers(args.input)
    write_text(render_catalog(papers), args.output)
    print(f"wrote {len(papers)} paper links to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
