#!/usr/bin/env python3
"""Merge and normalize RSS 2026 editorial fragments into one Typst include."""

from __future__ import annotations

import argparse
import re
import tempfile
from pathlib import Path


DEFAULT_ROOT = Path("content/posts")
DEFAULT_OUTPUT = DEFAULT_ROOT / "rss26-all-notes.typ.inc"
EDITORIAL_FILES = (
    "rss26-manipulation1-notes.typ.inc",
    "rss26-manipulation2-3-planning-notes.typ.inc",
    "rss26-imitation-vla-notes.typ.inc",
    "rss26-navigation-notes.typ.inc",
    "rss26-localization-perception-notes.typ.inc",
    "rss26-world-humanoid-control-notes.typ.inc",
    "rss26-remaining-sessions-notes.typ.inc",
)
SESSION_HEADINGS = {
    "Humanoids",
    "Control & Dynamics",
    "World Models & Memory",
}


def normalize_fragment(path: Path) -> list[str]:
    lines: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        if line.startswith("//"):
            continue
        if line.startswith("= "):
            heading = line[2:].strip()
            if heading in SESSION_HEADINGS:
                line = f"== {heading}"
            else:
                continue
        elif line.startswith("== "):
            heading = line[3:].strip()
            if re.match(r"^\d+\.\s", heading):
                paper_match = re.search(r"program/papers/(\d+)/", line)
                paper_id = paper_match.group(1) if paper_match else heading.split(".", 1)[0]
                heading = re.sub(r"^\d+\.\s+", f"{paper_id}. ", heading)
                line = f"=== {heading}"
        elif line.startswith("=== "):
            heading = line[4:].strip()
            paper_match = re.search(r"program/papers/(\d+)/", line)
            if paper_match:
                heading = re.sub(r"^\d+\.\s+", f"{paper_match.group(1)}. ", heading)
                line = f"=== {heading}"
        lines.append(line)
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return lines


def render(root: Path, catalog: Path) -> str:
    output = [
        "// Generated by tools/rss2026/merge_typst_notes.py. Do not edit this file manually.",
        "",
    ]
    for filename in EDITORIAL_FILES:
        fragment = root / filename
        normalized = normalize_fragment(fragment)
        if filename == "rss26-manipulation1-notes.typ.inc":
            output.extend(["== Manipulation 1", ""])
        output.extend(normalized)
        output.extend(["", ""])
    output.extend(["= 全部论文索引", ""])
    output.extend(catalog.read_text(encoding="utf-8").splitlines())
    return "\n".join(output).rstrip() + "\n"


def write_text(content: str, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=output.parent, prefix=f".{output.name}.", delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.replace(output)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_ROOT / "rss26-paper-catalog.typ.inc")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    missing = [args.root / filename for filename in EDITORIAL_FILES if not (args.root / filename).exists()]
    if missing or not args.catalog.exists():
        raise SystemExit("missing input files: " + ", ".join(str(path) for path in [*missing, args.catalog] if not path.exists()))
    write_text(render(args.root, args.catalog), args.output)
    print(f"wrote merged RSS 2026 notes to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
